import { CVTemplate } from '../types/template';
import { PALETTES_SOBER, PALETTES_VIBRANT } from '../theme/tokens';

export const atsModern: CVTemplate = {
  id: 'ats-modern',
  name: 'Moderne',
  description: 'Design épuré, respiration généreuse, titres de section affirmés.',
  category: 'ats',
  recommendedFor: ['corporate', 'dev', 'international'],
  supportsPhoto: true,
  palettes: [...PALETTES_SOBER, PALETTES_VIBRANT[0], PALETTES_VIBRANT[1]],
  defaultDensity: 'normal',
  headerVariants: ['clean', 'accent-bar', 'accent-light', 'accent-banner'],
  docx: {
    pageSize: 'A4',
    margins: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
    fonts: {
      heading: 'Arial',
      body: 'Arial',
    },
    headingSize: 30,
    bodySize: 22,
    lineSpacing: 340,
    sectionSpacing: 300,
    useColumns: false,
    useTables: false,
  },
  preview: {
    containerClass: 'max-w-[210mm] mx-auto bg-white shadow-lg px-14 py-12 text-gray-800 font-sans',
    headingClass: 'text-[12.5px] font-bold uppercase tracking-[0.22em] text-blue-900 border-b-2 border-blue-700 pb-2 mb-4 mt-8',
    entryClass: 'mb-6',
    titleClass: 'font-bold text-gray-900 text-[14px]',
    subtitleClass: 'font-medium text-blue-800 text-[12.5px]',
    dateClass: 'text-gray-600 text-[11.5px] tabular-nums italic mb-1.5',
    descriptionClass: 'text-gray-700 text-[12px] whitespace-pre-line leading-relaxed',
    skillsContainerClass: 'list-disc pl-6 grid grid-cols-1 gap-y-0.5',
    skillClass: 'text-[12px] text-gray-700',
    skillBadgeContainerClass: 'flex flex-wrap gap-2 mt-1',
    skillBadgeClass: 'inline-block px-3 py-1 text-[11px] font-medium bg-blue-50 text-blue-800 border border-blue-200 rounded-full',
    nameClass: 'text-[32px] font-bold uppercase tracking-[0.08em] text-gray-900 mb-1',
    headerTitleClass: 'text-[18px] font-semibold text-blue-800',
    contactClass: 'text-[12px] text-gray-600',
    summaryClass: 'text-[12px] text-gray-700 leading-relaxed',
  },
};
